#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ObjectivePerl
version:      0.04
version_from: ObjectivePerl.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
